services:
  website:
    build:
      args:
        ENV: development
    volumes:
      - ./docker/php.dev.ini:/usr/local/etc/php/php.ini
      - ./src/:/var/www/html
    command: bash -c "composer install && apache2-foreground"
