version: "3.7"

services:
  website:
    container_name: webserver
    depends_on:
      - db
    restart: always
    build:
      context: ./
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - bridge

  db:
    container_name: database
    build:
      context: ./
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - MYSQL_DATABASE=researchGrant
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=superSecret
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - bridge

  mailer:
    image: ilyasotkov/php-msmtp:7-fpm-alpine
    container_name: mailer
    build:
      context: ./
      dockerfile: Dockerfile-mailer
    secrets:
      - gmail_password
    volumes:
      - ./msmtprc:/etc/msmtprc
      - ./send.php:/send.php
    networks:
      - bridge

networks:
  bridge:
    name: cstem-scholars-network

secrets:
  gmail_password:
    file: ./gmail_password

volumes:
  dbData: {}
